service: seals-api

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action: secretsmanager:GetSecretValue
      Resource: "*"

plugins:
  - serverless-python-requirements

functions:
  get:
    handler: lambdas/get.get
    events:
      - http:
          path: beaches
          method: get
          cors: true